#!/usr/bin/env bash

# имя функции для запуска
FUNCTION=
if [ ! -z $1 ]; then
    FUNCTION="$1"
fi

showHelp(){
  echo -e "one - используйте в первый раз, правильная настройка групп и контейнеров(потребует пароль sudo)"
  echo -e "try - попробовать произвести настройку без sudo(скорее всего не сможет добавить группы)"
  echo -e "up - запустит проект(PHP7.2-nginx-apache2-mysql5.7-adminer)"
  echo -e "upfull - запустит FULL проект(up()+MonitoringService-Networks)"
  echo -e "stop - усыпит и остановит все контейнеры проекта"
  echo -e "clear - сборщик мусора"
}

one(){
sudo groupadd docker
sudo usermod -aG docker $USER
sudo service docker restart
}

try(){
groupadd docker
usermod -aG docker $USER
service docker restart
docker-compose up --build -d
docker ps
}

up(){
docker-compose -f simple.yml up --build -d
}

upfull(){
docker-compose -f full.yml up --build -d
}

stop(){
docker-compose stop
docker-compose down
}

clear(){
docker image prune
docker volume prune
}


   if [ ! -z $(type -t $FUNCTION | grep function) ]; then
        init-xdebug
        check-env
        $1
    else
        showHelp
fi
