version: '3.1'

services:

  nginx:
    image: nginx:latest
    ports:
      - "7666:80"
      - "7771:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    build: ./images/php
    links:
      - db
    volumes:
      - ./www:/var/www
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./mysql:/var/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example

  adminer:
    build: ./images/adminer
    restart: always
    ports:
      - 8080:8080
