version: '3.1'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ./www:/var/www/html
      - ./hosts/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - "7666:80"
      - "7771:443"
    volumes:
      - ./www:/var/www/html
      - ./hosts/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - apache

  php:
    build: ./images/php
    links:
      - db
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./images/mysql:/var/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example

  adminer:
    build: ./images/adminer
    restart: always
    ports:
      - 8080:8080
